### ISSUE TITLE
Using with web applications

### ISSUE THREAD

**Issue by poganytamas** [PDFTron/PDFNetLoader#4]
With the current setup, pdfnetloader does not work with web applications, because during the build (using the nuget package), the pdfnet directory will be located in the bin/pdfnet directory, not like console apps / winform apps.

I know there is a solution seting the path property, but in the code instead of using AppDomain.CurrentDomain.SetupInformation.ApplicationBase I suggest checking if it is a web application or not, something like this:

`if (String.IsNullOrEmpty(AppDomain.CurrentDomain.RelativeSearchPath))
        {
            //exe folder for WinForms, Consoles, Windows Services
            return AppDomain.CurrentDomain.BaseDirectory;
        }
        else
        {
            //bin folder for Web Apps 
            return AppDomain.CurrentDomain.RelativeSearchPath;
        }`

**Comment by rbarrpdftron** [comment]
@poganytamas The PDFNetLoader is mainly aimed at making sure our SDK samples work, regardless of process architecture.

>pdfnetloader does not work with web applications
If you are deploying to your own server, then I would imagine you already know if your server is 32bit or 64bit, in which case you do not need PDFNetLoader, and instead always deploy the correct PDFNet.dll.

Otherwise, yes, the Path property is there to handle alternate environments.
